MVC_SIvPaVS/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SIvPaVS.Controllers
{
    public class CompanyController : Controller
    {
        // GET: Company
        public ActionResult CompanyAddress()
        {
            return PartialView();
        }


    }
}

MVC_SIvPaVS/Controllers/ReceiptController.cs
using SIvPaVS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SIvPaVS.Controllers
{
    public class ReceiptController : Controller
    {
        // GET: Receipt
        public ActionResult Receipt()
        {

            if (ReceiptModel.Receipt == null) new ReceiptModel();
            ViewData.Model = ReceiptModel.Receipt;
            return View();
        }

        [HttpPost]
        public ActionResult Index(Item item)
        {

            addNewItem(item);


            ViewData.Model = ReceiptModel.Receipt;

            //ViewData.Model = new HomeModel() { CompanyTitle = "test", TotalPrice = 145 };
            return View("~/Views/Receipt/Receipt.cshtml");
        }

       // [HttpPost]
        public ActionResult DeleteItem(string ID)
        {

            deleteItem(ID);


            ViewData.Model = ReceiptModel.Receipt;

            //ViewData.Model = new HomeModel() { CompanyTitle = "test", TotalPrice = 145 };
            return View("~/Views/Receipt/Receipt.cshtml");
        }

        private void deleteItem(string ID)
        {


            int position = 0;
            foreach (var item in ReceiptModel.Receipt.Items)
            {
                if (item.Id == ID)
                    break;
                
                position++;
            }


            var items = ReceiptModel.Receipt.Items;
            ReceiptModel.Receipt.Items = new Item[items.Count() -1];
            int receiptItemCounter = 0;
            int itemsCounter = 0;

            foreach (var item in items)
            {
                if (itemsCounter != position)
                    ReceiptModel.Receipt.Items[receiptItemCounter++] = item;

                itemsCounter++;
            }



        }

        private void addNewItem(Item item)
        {
            var items = ReceiptModel.Receipt.Items;
            ReceiptModel.Receipt.Items = new Item[items.Count() + 1];

            
            int counter = 0;
            foreach (var it in items)
            {
                ReceiptModel.Receipt.Items[counter++] = it;
            }
            item.Id = (++ ReceiptModel.IDCounter).ToString();
            ReceiptModel.Receipt.Items[counter] = item;

        }

        public ActionResult Company()
        {
            return PartialView();
        }


        public ActionResult Items()
        {
            return PartialView();
        }

        public ActionResult CompanyAddress()
        {
            return PartialView();
        }

        public ActionResult CreateItem()
        {
            return View();
        }


        [HttpPost]
        public ActionResult CreateItem(Item item)
        {

            addNewItem(item);
            ViewData.Model = ReceiptModel.Receipt;

            //ViewData.Model = new HomeModel() { CompanyTitle = "test", TotalPrice = 145 };
            return View();
        }


    }
}

MVC_SIvPaVS/Views/Receipt/Company.cshtml
@model SIvPaVS.Xsd.Businessobject


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Spoločnosť</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Companyregnum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Companyregnum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Companyregnum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vatregnum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vatregnum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vatregnum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div>
            @Html.Partial("CompanyAddress", Model.Address)
        </div>

        @*<div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>*@
    </div>
}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_SIvPaVS/Views/Receipt/CompanyAddress.cshtml
@model SIvPaVS.Models.Address


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Adresa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>*@
    </div>
}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_SIvPaVS/Views/Receipt/CreateItem.cshtml
@model SIvPaVS.Models.Item

@{
    ViewBag.Title = "CreateItem";
}

<h2>Pridať položku</h2>


@using (Html.BeginForm("Index", "Receipt", "POST")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @*<h4>Item</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Pridať" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Späť", "Receipt/Receipt")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_SIvPaVS/Views/Receipt/Items.cshtml
@model IEnumerable<SIvPaVS.Models.Item>

<p>
    @Html.ActionLink("Pridať položku", "CreateItem")
</p>
<h4>Položky</h4>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            Celkom
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalPrice)
        </td>
        <td>
        @*    @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
    *            @Html.ActionLink("Details", "Details", new { id=item.Id }) |*@
            @Html.ActionLink("Odstrániť položku", "DeleteItem", new { id=item.Id })
        </td>
    </tr>
}

</table>

MVC_SIvPaVS/Views/Receipt/Receipt.cshtml
@model SIvPaVS.Models.ReceiptModel

@{
    ViewBag.Title = "Receipt";
}

<h2>Pokladničný blok</h2>


@using (Html.BeginForm(@*"Receipt","Receipt","POST"*@))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Slúži ako dańový doklad.</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div>
            @Html.Partial("Company", Model.Provider)
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Issuedat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Issuedat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Issuedat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Taxcode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Taxcode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Taxcode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div>
            @Html.Partial("Items", Model.Items)
        </div>


        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Uložiť" class="btn btn-default" />
            </div>
        </div>
    </div>


}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}